src/home/urls.py
from django.conf.urls import url
from .views import HomeTemplateView, dashboard, usuarios

# urlpatterns = [
#     url(r'^$', views.Dashboard, name='index'),
#     #url(r'^$', HomeTemplateView.as_view(), name='index'),
# ]

urlpatterns = [
    url(r'^$', HomeTemplateView.as_view(), name='index'),
    url(r'^dashboard$', dashboard, name='dashboard'),
    url(r'^usuarios$', usuarios, name='usuarios'),

]

src/mantenedor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .models import *
from .views import *
from .models import *
from mantenedor import views


urlpatterns = [
    #producto
    url(r'^mantenedor/listar/producto$', ProductoList.as_view(), name='producto_listar'),
    url(r'^mantenedor/crear/producto$', ProductoCreate.as_view(), name='producto_crear'),
    url(r'^mantenedor/editar/producto/(?P<pk>\d+)/$', ProductoUpdate.as_view(), name='producto_editar'),
    url(r'^mantenedor/eliminar/producto_estado/(?P<pk>\d+)/$', ProductoEstado.as_view(), name='producto_estado'),
    url(r'^mantenedor/listar/producto/baja$', ProductoDeBajaList.as_view(), name='producto_listar_baja'),
    url(r'^mantenedor/listar/producto/mantencion$', ProductoMantencionList.as_view(), name='producto_listar_mantencion'),
    #url(r'^mantenedor/eliminar/producto/(?P<pk>\d+)/$', ProductoDelete.as_view(), name='producto_eliminar'),
    #categoria
    url(r'^mantenedor/listar/categoria$', CategoriaList.as_view(), name='categoria_listar'),
    url(r'^mantenedor/crear/categoria$', CategoriaCreate.as_view(), name='categoria_crear'),
    url(r'^mantenedor/editar/categoria/(?P<pk>\d+)/$', CategoriaUpdate.as_view(), name='categoria_editar'),
    url(r'^mantenedor/eliminar/categoria/(?P<pk>\d+)/$', CategoriaDelete.as_view(), name='categoria_eliminar'),
    #BootstrapDialog
    url(r'^mantenedor/listar/producto/dialog$', views.total_productos, name='producto_listar_dialog'),
    url(r'^mantenedor/listar/producto/dialog2$', views.productos_disponibles, name='producto_listar_dialog2'),
    url(r'^mantenedor/listar/producto/dialog3$', views.productos_mantencion, name='producto_listar_dialog3'),
    url(r'^mantenedor/listar/producto/dialog4$', views.productos_prestados, name='producto_listar_dialog4'),
    url(r'^mantenedor/listar/producto/dialog5$', views.productos_baja, name='producto_listar_dialog5'),
]

src/prestamo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    #modelwidget
    url(r'^select2/', include('django_select2.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('users.urls', namespace='usuario')),

    #URL de mantenedor

    url(r'^', include('mantenedor.urls', namespace="mantenedor")),

    #Url de Prestamos

    url(r'^', include('prestamos.urls', namespace="prestamos")),

    #Url de Laboratorio

    url(r'^laboratorio/', include('laboratorio.urls', namespace="laboratorio")),

    #Url de Reportes

    url(r'^reportes/', include('reportes.urls', namespace="reportes")),

    # URL del Home

    url(r'^', include('home.urls', namespace='home')),

    # URL Cuentas de usuario

    url(r'^accounts/', include('allauth.urls')),

    # urls de login y de recuperacion de contraseña

    url(r'^password/reset/', password_reset,
        {'template_name': 'account/password_reset_email_form.html',
         'email_template_name': 'account/password_reset_email.html'},
        name='password_reset'),

    url(r'^password/reset-done', password_reset_done,
        {'template_name': 'account/password_reset_email_done.html'},
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'account/password_reset_email_confirm.html'},
        name='password_reset_confirm'),

    url(r'^reset/done', password_reset_complete,
        {'template_name': 'account/password_reset_email_complete.html'},
        name='password_reset_complete'),

]

src/prestamos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .models import *
from .views import *
from prestamos import views
#Prestamo

urlpatterns = [
    url(r'^prestamos/listar/prestamo$', PrestamoList.as_view(), name='prestamo_listar'),
    #url(r'^prestamos/crear/prestamo$', views.user, name='prestamo_crear_prestamo'),
    url(r'^prestamos/editar/prestamo/(?P<pk>\d+)/$', PrestamoUpdate.as_view(), name='prestamo_editar'),
    url(r'^prestamos/eliminar/prestamo/(?P<pk>\d+)/$', PrestamoDelete.as_view(), name='prestamo_eliminar'),
    url(r'^prestamos/crear/prestamos$', PrestamoCreate.as_view(), name='prestamo_crear'),
    url(r'^prestamos/devolucion/(?P<pk>\d+)/$', Devolucion.as_view(), name='devolucion'),
    url(r'^prestamos/listar/devoluciones$', DevolucionList.as_view(), name='devolucion_listar'),
    url(r'^prestamos/listar/retrasos$', RetrasosList.as_view(), name='retrasos'),
    url(r'^prestamos/listar/danos$', DanosList.as_view(), name='danos'),

    url(r'^prestamos/listar/prestamo/dialog1$', views.prestamo_activo, name='list_prestamos'),
    url(r'^prestamos/listar/prestamo/dialog2$', views.prestamo_atrasado, name='list_prestamos_atrasados'),
]

src/reportes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *
from reportes import views


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='hom'),
    url(r'^report$', Reporte.as_view(), name='report'),
    url(r'^report/activo$', ReporteActivo.as_view(), name='report_activo'),
    url(r'^api/data/', get_data, name='api-data'),
    url(r'^api/chart/data/', ChartData.as_view()),
    #url(r'^reportes/pdf$', views.report_pdf, name='pdf'),
]

src/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^registrar', views.UserCreateView.as_view(), name="registrar"),
    url(r'^editar/(?P<pk>[0-9]+)/$', views.UserUpdateView.as_view(), name='editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', views.UserDeleteView.as_view(), name="eliminar"),
    url(r'^$', views.UserListView.as_view(), name='listar'),

    #url(r'^account/', views.UserAccountView.as_view(), name='account'),

    
]

src/templates/base/_navbar_left.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs"> <strong class="font-bold"><i class="fas fa-user-circle"></i> {{ user.username }}</strong></span>
                            <span class="text-muted text-xs block">
                                {% if user.is_staff %}
                                    Administrador
                                {% else %}
                                    <div class="dropdown profile-element">
                                        {{ user.groups.all.0.name }}
                                    </div>
                                    <div class="dropdown profile-element">    
                                        {{ user.groups.all.1.name }}
                                    </div>
                                    <div class="dropdown profile-element"> 
                                        {{ user.groups.all.2.name }}
                                    </div>    
                                    <div class="dropdown profile-element">
                                        {{ user.groups.all.3.name }}
                                    </div>
                                {% endif %}
                                <b class="caret"></b>
                            </span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        {% if user.is_superuser %}
                            <li>
                                <a href="/admin/" target="_blank">
                                    <i class="fa fa-cog"></i> Administrar
                                </a>
                            </li>
                            <li role="separator" class="divider"></li>
                        {% endif %}
                        <li>
                            <a href="{% url 'account_change_password' %}">
                                <i class="fa fa-key"></i>
                                Cambiar contraseña
                            </a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="{% url 'account_logout' %}">
                                <i class="fas fa-sign-out-alt"> </i>
                                Cerrar Sesion
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="logo-element"><i class="fas fa-user-circle"></i></div>
            </li>


            <li class="#">
              <a href="{% url 'home:index' %}">
                <i class="fa fa-home" data-toggle="tooltip" data-placement="right" title="Home"></i>
                <span class="nav-label">Inicio</span>
              </a>
            </li>

              <li class="#">
              <a href="{% url 'home:dashboard' %}">
                <i class="fas fa-chart-line" data-toggle="tooltip" data-placement="right" title="Dashboard"></i>
                <span class="nav-label">Dashboard</span>
              </a>
            </li>


                            <!-- Usuario -->

            {% if perms.auth.view_user or perms.auth.add_user %}
            <li class="#">
              <a href="#">
                <i class="fas fa-users" data-toggle="tooltip" data-placement="right" title="Usuarios"></i>
                <span class="nav-label">Usuarios</span>
                <span class="fa arrow"></span>
              </a>
              <ul class="nav nav-second-level collapse">
                <li class="">
                  <a href="{% url 'usuario:listar' %}">
                    <i class="fa fa-list"></i>Listar
                  </a>
                </li>
                {% if perms.auth.add_user %}
                <li class="">
                  <a href="{% url 'usuario:registrar' %}">
                    <i class="fa fa-plus"></i>Registrar
                  </a>
                </li>
                {% endif %}
              </ul>
            </li>
            {% endif %}

            <!---------------- Mantenedor ----------------------->
            {% if perms.mantenedor.add_producto %}
            <li class="#">
                <a href="#">
                    <i class="fas fa-pen-square" data-toggle="tooltip" data-placement="right" title="Mantenedor"></i>
                    <span class="nav-label">Mantenedor</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level collapse">

                    {% if perms.mantenedor.add_producto %}
                    <li class="#">
                        <a href="#">
                            <i class="fas fa-chevron-circle-right"></i>
                            <span class="nav-label">Producto</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-third-level collapse">
                            <li class="">
                                <a href="{% url 'mantenedor:producto_listar' %}">
                                    <i class="fas fa-bars"></i>Listar
                                </a>
                            </li>
                    {% if perms.mantenedor.add_producto %}
                            <li class="#">
                                <a href="{% url 'mantenedor:producto_crear' %}">
                                    <i class="fas fa-plus-circle"></i>Registrar
                                </a>
                            </li>
                            {% endif %}
                            <li class="#">
                                <a href="{% url 'mantenedor:producto_listar_mantencion' %}">
                                    <i class="fas fa-wrench"></i>En Mantencion
                                </a>
                            </li>

                            <li class="#">
                                <a href="{% url 'mantenedor:producto_listar_baja' %}">
                                    <i class="fas fa-trash"></i>Dados de Baja
                                </a>
                            </li>
                        </ul>
                    </li>
                    {% endif %}

                <!--Categoria-->
                    {% if perms.mantenedor.add_categoria %}
                     <li class="#">
                        <a href="#">
                            <i class="fas fa-chevron-circle-right"></i>
                            <span class="nav-label">Categoria</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-third-level collapse">
                            <li class="">
                                <a href="{% url 'mantenedor:categoria_listar' %}">
                                    <i class="fas fa-bars"></i>Listar
                                </a>
                            </li>
                            {% if perms.mantenedor.add_categoria %}
                            <li class="">
                                <a href="{% url 'mantenedor:categoria_crear' %}">
                                    <i class="fas fa-plus-circle"></i>Registrar
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
            </li>





{% if perms.prestamos.add_prestamo %}
            <li class="#">
                <a href="#">
                    <i class= "fas fa-handshake"data-toggle="tooltip" data-placement="right" title="Prestamos"></i>
                    <span class="nav-label">Prestamos</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level collapse">
                    <li class="">
                        <a href="{% url 'prestamos:prestamo_listar' %}">
                            <i class="fas fa-bars"></i>Listar Prestamos
                        </a>
                    </li>
                {% if perms.prestamos.add_prestamo %}
                    <li class="">
                        <a href=" {% url 'prestamos:prestamo_crear' %}">
                            <i class="fas fa-plus-circle"></i>Nuevo Prestamo
                        </a>
                    </li>
                {% endif %}
                    <li class="">
                        <a href=" {% url 'prestamos:devolucion_listar' %}">
                            <i class="fas fa-undo-alt"></i>Historial Devoluciones
                        </a>
                    </li>

                    <li class="">
                        <a href=" {% url 'prestamos:retrasos' %}">
                            <i class="fas fa-clock"></i>Usuarios con Atrasos en Devolucion
                        </a>
                    </li>

                    <li class="">
                        <a href=" {% url 'prestamos:danos' %}">
                            <i class="fas fa-exclamation-triangle"></i>Usuarios con Daños en Productos
                        </a>
                    </li>

                </ul>
            </li>
        {% endif %}


             <li class="#">
                  <a href="#">
                    <i class="fas fa-chart-bar" data-toggle="tooltip" data-placement="right" title="Reportes"></i>
                    <span class="nav-label">Reportes</span>
                    <span class="fa arrow"></span>
                  </a>
                  <ul class="nav nav-second-level collapse">
                    <li class="">
                      <a href="{% url 'reportes:hom' %}">
                        <i class="fas fa-file-alt"></i>Generar Reportes
                      </a>
                    </li>
                  </ul>
                </li>


             <li class="#">
                  <a href="#">
                    <i class="fas fa-desktop" data-toggle="tooltip" data-placement="right" title="Laboratorio"></i>
                    <span class="nav-label">Laboratorio</span>
                    <span class="fa arrow"></span>
                  </a>
                  <ul class="nav nav-second-level collapse">
                    <li class="">
                      <a href="{% url 'laboratorio:calendar' %}">
                        <i class="fas fa-eye"></i>Ver Horario
                      </a>
                    </li>
                  </ul>
                </li>
        </ul>
        </li>
        </ul>
        </li>
        </ul>
    </div>
</nav>
<script>
    $(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>

src/templates/base/_notifications.html
<script>
function showToast(level, message) {
  if (level == 'success' || level == 'info') {
    toastr.info(message);
    return;
  }

  if (level == 'warning' || level == 'error') {
    toastr.error(message);
    return;
  }

  toastr.warning(message);
}

{% if messages %}
    {% for message in messages %}
      {% if message.tags %}
        showToast('{{ message.tags }}', '{{ message }}');
      {% else %}
        showToast('success', '{{ message }}');
      {% endif %}
    {% endfor %}
{% endif %}
</script>

src/templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SISTEMA | {% block head_title %}Inicio{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">
    <!--<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">-->
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet"><link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'ionicons/css/ionicons.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesome-free\web-fonts-with-css\css\fontawesome-all.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.3/jquery.min.js"></script>-->
    <!--<link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet" type="text/css"/>-->
    <link href="{% static 'animate.css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'animate.css/animate.css/animate.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/plugins/fullcalendar/fullcalendar.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/fullcalendar/fullcalendar.print.css' %}" rel="stylesheet" media="print">
    <link href="{% static 'select2/dist/css/select2.css' %}" rel="stylesheet">
    <link href="{% static 'select2/dist/css/select2.css/select2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/alertify.bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/alertify.core.css' %}" rel="stylesheet">
    <link href="{% static 'css/alertify.default.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-dialog.min.css' %}" rel="stylesheet">

    <!--<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/css/bootstrap-dialog.min.css" rel="stylesheet"/>-->

    {{ form.media }}
    {% block css %}{% endblock %}
</head>

<body>
<div id="wrapper">
    {% include 'base/_navbar_left.html' %}
    <div id="page-wrapper" class="white-bg">
        {% include 'base/_navbar_top.html' %}
        <div class="wrapper wrapper-content animated fadeInUp">
            {% block content %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center m-t-lg">
                            <h1>Bienvenido a Sistema Prestamo</h1>
                            <small>...</small>
                        </div>
                    </div>
                </div>
            {% endblock %}
        </div>
        <div class="footer">
            <div class="pull-right">Creado por <strong>Esteban Pando E. - Gonzalo Sepúlveda N. - Claudio Contreras B.</strong></div>
            <div><strong>Copyright</strong> Virginio Gomez &copy; 2018</div>
        </div>
    </div>
</div>

<!-- Mainly scripts -->


<script src="{% static 'js/plugins/fullcalendar/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/fullcalendar/jquery.min.js' %}"></script>


<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!--<script src="{% static 'js/plugins/toastr/toastr.min.js' %}"></script>-->
<script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
<script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static 'js/inspinia.js' %}"></script>
<script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
<script src="{% static 'js/bootstrap-dialog.js' %}"></script>


<script src="{% static 'js/bootstrap.min.js'%}"></script>

<script src="{% static 'select2/dist/js/select2.full.js' %}"></script>
<!--<script src="{% static 'select2/dist/js/select2.full.js/select2.full.min.js' %}"></script>-->
<script src="{% static 'select2/dist/js/select2.js' %}"></script>
<!--<script src="{% static 'select2/dist/js/select2.js/select2.min.js' %}"></script>-->
<!--<script src="{% static 'select2/dist/js/i18n/es.js' %}"></script>-->

<script src="{% static 'select2/src/js/jquery.select2.js' %}"></script>
<script src="{% static 'select2/src/js/select2/i18n/es.js' %}"></script>


<script src="{% static 'js/plugins/fullcalendar/fullcalendar.min.js' %}" ></script>
<script src="{% static 'js/plugins/fullcalendar/locale/es.js' %}" ></script>

<script src="{% static 'js/alertify.js' %}" ></script>
<script src="{% static 'js/alertify.min.js' %}" ></script>


{% include "base/_notifications.html" %}


<script>
  $(function() {
    var activePage = stripTrailingSlash(window.location.pathname);

    function stripTrailingSlash(str) {
      if (str.substr(-1) == '/') {
        return str.substr(0, str.length - 1);
      }

      return str;
    }

    var pageActivated = false;

    $('.nav li a').each(function(){
      var currentPage = stripTrailingSlash($(this).attr('href'));

      if (activePage == currentPage) {
        $(this).parent().addClass('active');

        $(this).parent().parent().parent().parent().addClass('in');
        $(this).parent().parent().parent().parent().parent().addClass('active')

        var ul = $(this).closest('ul.collapse');
        if (ul) {
          $(ul).addClass('in');
          $(ul).closest('li').addClass('active');
          pageActivated = true;
        }
      }
    });

    if (!pageActivated) {
      $('.nav li a').each(function() {
        var currentPage = stripTrailingSlash($(this).attr('href'));

        if (activePage.indexOf(currentPage) !== -1) {
          $(this).addClass('active');
          var ul = $(this).closest('ul.collapse');

          if (ul) {
            $(ul).addClass('in');
            $(ul).closest('li').addClass('active');
          }
        }
      });
    }
  });

  $('#dialog').click(function() {
      var dialogo = BootstrapDialog.show({
          title: 'Total de Productos',
          message: $('<div></div>').load("{% url 'mantenedor:producto_listar_dialog' %}"),
          type: BootstrapDialog.TYPE_INFO,
          buttons:[{
              label: 'Cerrar',
            cssClass: 'btn-info',
              action: function(dialog){
                  dialog.close();
              }
          }]
      });
  });

   $('#dialog1').click(function() {
      var dialogo = BootstrapDialog.show({
          title: 'Prestamos Activos',
          message: $('<div></div>').load("{% url 'prestamos:list_prestamos' %}"),
          type: BootstrapDialog.TYPE_SUCCESS,
          buttons:[{
              label: 'Cerrar',
            cssClass: 'btn-primary',
              action: function(dialog){
                  dialog.close();
              }
          }]
      });
  });

   $('#e').click(function() {
      var dialogo = BootstrapDialog.show({
          title: 'Reserva de Laboratorio',
          message: $('<div></div>').load("{% url 'laboratorio:list_reservas' %}"),
          type: BootstrapDialog.TYPE_WARNING,
          buttons:[{
              label: 'Cerrar',
            cssClass: 'btn-warning',
              action: function(dialog){
                  dialog.close();
              }
          }]
      });
  });

   $('#c').click(function() {
      var dialogo = BootstrapDialog.show({
          title: 'Prestamos Atrasados',
          message: $('<div></div>').load("{% url 'prestamos:list_prestamos_atrasados' %}"),
          type: BootstrapDialog.TYPE_DANGER,
          buttons:[{
              label: 'Cerrar',
            cssClass: 'btn-danger',
              action: function(dialog){
                  dialog.close();
              }
          }]
      });
  });

  $('#d').click(function() {
      var dialogo = BootstrapDialog.show({
          title: 'Productos Disponibles',
          message: $('<div></div>').load("{% url 'mantenedor:producto_listar_dialog2' %}"),
          type: BootstrapDialog.TYPE_PRIMARY,
          buttons:[{
              label: 'Cerrar',
            cssClass: 'btn-success',
              action: function(dialog){
                  dialog.close();
              }
          }]
      });
  });

  $('#reparacion').click(function() {
      var dialogo = BootstrapDialog.show({
          title: 'Productos en Mantencion',
          message: $('<div></div>').load("{% url 'mantenedor:producto_listar_dialog3' %}"),
          type: BootstrapDialog.TYPE_INFO,
          buttons:[{
              label: 'Cerrar',
            cssClass: 'btn-info',
              action: function(dialog){
                  dialog.close();
              }
          }]
      });
  });

  $('#prestados').click(function() {
      var dialogo = BootstrapDialog.show({
          title: 'Productos Actualmente en Prestamo',
          message: $('<div></div>').load("{% url 'mantenedor:producto_listar_dialog4' %}"),
          type: BootstrapDialog.TYPE_SUCCESS,
          buttons:[{
              label: 'Cerrar',
            cssClass: 'btn-primary',
              action: function(dialog){
                  dialog.close();
              }
          }]
      });
  });

  $('#baja').click(function() {
      var dialogo = BootstrapDialog.show({
          title: 'Productos Dados de Baja del Sistema',
          message: $('<div></div>').load("{% url 'mantenedor:producto_listar_dialog5' %}"),
          type: BootstrapDialog.TYPE_DANGER,
          cssClass: 'type-warning',
          buttons:[{
              label: 'Cerrar',
            cssClass: 'btn-danger',
              action: function(dialog){
                  dialog.close();
              }
          }]
      });
  });

  $('#usuarios').click(function() {
      var dialogo = BootstrapDialog.show({
          title: 'Usuarios Actuales en el Sistema',
          message: $('<div></div>').load("{% url 'home:usuarios' %}"),
          type: BootstrapDialog.SUCCESS,
          cssClass: 'type-success',
          buttons:[{
              label: 'Cerrar',
            cssClass: 'btn-success',
              action: function(dialog){
                  dialog.close();
              }
          }]
      });
  });




  $(document).ready(function() {

        $('#usuario').select2({
                width:'100%',
                theme: 'default',
                language : 'es',
                placeholder: 'Seleccione Usuario'
            });

        $('#calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay,listWeek'

            },
            nowIndicator: true,
            minTime: "08:00:00",
            maxTime: "19:00:00",
            locale: 'es',
            weekends : false,
            editable: true,

            events: [

                {% for i in eventlist %}

                {
                    id : '{{ i.id }}',
                    title: "{{ i.title }}" + " " + "{{ i.usuario__username}}",
                    start: '{{ i.start|date:"Y-m-d H:i"}}',
                    end : '{{ i.end|date:"Y-m-d H:i"}}',

                },

                {% endfor %}

            ],

            dayClick: function(date, jsEvent, view) {



                var dialogo = BootstrapDialog.show({
                    title: 'Registrar Evento',
                    type: BootstrapDialog.TYPE_SUCCESS,

                    message: $('<div></div>').load("{% url 'laboratorio:laboratorio_modal' %}"),
                    buttons:[{
                       label: 'Guardar Evento',
                        cssClass: 'btn-primary',
                        action: function (dialog) {
                            var datos=$("#FormularioEventos").serialize();
                            console.log(datos);
                            $.post("{% url 'laboratorio:laboratorio_modal' %}",datos,function (data) {
                                console.log(data);
                                NuevoEvento = {
                                    title: $('#id_title').val() + $('#id_usuario').val(),
                                    start: $('#id_start').val(),
                                    end : $('#id_end').val(),

                                }
                                $('#calendar').fullCalendar('renderEvent',NuevoEvento);
                                dialog.close();

                            });
                        }
                    }]
                });

            },

            eventClick:function(calEvent, jsEvent, view) {

                var dialogo = BootstrapDialog.show({
          title: 'Detalle de Evento',
          message: $('<div></div>').load("/laboratorio/editar/"+calEvent.id+"/"),
          type: BootstrapDialog.TYPE_SUCCESS,
          buttons:[{
              label: 'Cerrar',
            cssClass: 'btn-primary',
              action: function(dialog){
                  dialog.close();
              }
          }]
      });

            },

            eventLimit : true,
            views : {
                agenda: {
                    eventLimit : 4
                }
            },


        });


    });

</script>



<script>
    $(document).ready(function() {
        $('#id_id_producto').select2({
            width:'100%',
            theme: 'default',
            placeholder: 'Seleccione Producto',
            language: "es"
        });
    });


</script>

<script>
    $(document).ready(function() {
        $('#usuario').select2({
            width:'100%',
            theme: 'default',
            language : 'es',
            placeholder: 'Seleccione Usuario'
        });
    });


</script>

{% block after_content %} {% endblock %}
</body>
</html>