src/home/urls.py
from django.conf.urls import url
from .views import HomeTemplateView, dashboard, usuarios

# urlpatterns = [
#     url(r'^$', views.Dashboard, name='index'),
#     #url(r'^$', HomeTemplateView.as_view(), name='index'),
# ]

urlpatterns = [
    url(r'^$', HomeTemplateView.as_view(), name='index'),
    url(r'^dashboard$', dashboard, name='dashboard'),
    url(r'^usuarios$', usuarios, name='usuarios'),

]

src/mantenedor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .models import *
from .views import *
from .models import *
from mantenedor import views


urlpatterns = [
    #producto
    url(r'^mantenedor/listar/producto$', ProductoList.as_view(), name='producto_listar'),
    url(r'^mantenedor/crear/producto$', ProductoCreate.as_view(), name='producto_crear'),
    url(r'^mantenedor/editar/producto/(?P<pk>\d+)/$', ProductoUpdate.as_view(), name='producto_editar'),
    url(r'^mantenedor/eliminar/producto_estado/(?P<pk>\d+)/$', ProductoEstado.as_view(), name='producto_estado'),
    url(r'^mantenedor/listar/producto/baja$', ProductoDeBajaList.as_view(), name='producto_listar_baja'),
    url(r'^mantenedor/listar/producto/mantencion$', ProductoMantencionList.as_view(), name='producto_listar_mantencion'),
    #url(r'^mantenedor/eliminar/producto/(?P<pk>\d+)/$', ProductoDelete.as_view(), name='producto_eliminar'),
    #categoria
    url(r'^mantenedor/listar/categoria$', CategoriaList.as_view(), name='categoria_listar'),
    url(r'^mantenedor/crear/categoria$', CategoriaCreate.as_view(), name='categoria_crear'),
    url(r'^mantenedor/editar/categoria/(?P<pk>\d+)/$', CategoriaUpdate.as_view(), name='categoria_editar'),
    url(r'^mantenedor/eliminar/categoria/(?P<pk>\d+)/$', CategoriaDelete.as_view(), name='categoria_eliminar'),
    #BootstrapDialog
    url(r'^mantenedor/listar/producto/dialog$', views.total_productos, name='producto_listar_dialog'),
    url(r'^mantenedor/listar/producto/dialog2$', views.productos_disponibles, name='producto_listar_dialog2'),
    url(r'^mantenedor/listar/producto/dialog3$', views.productos_mantencion, name='producto_listar_dialog3'),
    url(r'^mantenedor/listar/producto/dialog4$', views.productos_prestados, name='producto_listar_dialog4'),
    url(r'^mantenedor/listar/producto/dialog5$', views.productos_baja, name='producto_listar_dialog5'),
]

src/prestamo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    #modelwidget
    url(r'^select2/', include('django_select2.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('users.urls', namespace='usuario')),

    #URL de mantenedor

    url(r'^', include('mantenedor.urls', namespace="mantenedor")),

    #Url de Prestamos

    url(r'^', include('prestamos.urls', namespace="prestamos")),

    #Url de Laboratorio

    url(r'^laboratorio/', include('laboratorio.urls', namespace="laboratorio")),

    #Url de Reportes

    url(r'^reportes/', include('reportes.urls', namespace="reportes")),

    # URL del Home

    url(r'^', include('home.urls', namespace='home')),

    # URL Cuentas de usuario

    url(r'^accounts/', include('allauth.urls')),

    # urls de login y de recuperacion de contraseña

    url(r'^password/reset/', password_reset,
        {'template_name': 'account/password_reset_email_form.html',
         'email_template_name': 'account/password_reset_email.html'},
        name='password_reset'),

    url(r'^password/reset-done', password_reset_done,
        {'template_name': 'account/password_reset_email_done.html'},
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'account/password_reset_email_confirm.html'},
        name='password_reset_confirm'),

    url(r'^reset/done', password_reset_complete,
        {'template_name': 'account/password_reset_email_complete.html'},
        name='password_reset_complete'),

]

src/mantenedor/models.py
from django.db import models
#from mantenedor.models import Categoria
from django.db.models import Q

# Create your models here.


class Categoria(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    nombre = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.nombre


class ProductoManager(models.Manager):

    def find(self, search):
        if not search:
            return self

        qs = Q(codigo__icontains=search) | \
             Q(marca__icontains=search) | \
             Q(descripcion__icontains=search)

        return self.filter(qs)


class Producto(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    codigo = models.CharField(max_length=100, blank=False, null=False)
    marca = models.CharField(max_length=100, blank=False, null=False, default="")
    descripcion = models.CharField(max_length=100, blank=True, null=True)
    id_categoria_id = models.ForeignKey(Categoria, blank=True, null=True, default=1)
    estado = models.CharField(max_length=100, blank=False, null=False,default=1, choices=(('1', 'Disponible'), ('0', 'Dado de Baja'), ('2', 'En Mantención')))

    objects = ProductoManager()

    def __str__(self):
        return self.codigo

src/mantenedor/forms.py
from django import forms
from .models import *


class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto

        fields = [
            'codigo',
            'marca',
            'descripcion',
            'id_categoria_id',
            'estado'
        ]
        labels = {
            'codigo': 'Codigo',
            'marca': 'Marca',
            'estado': 'Estado',
            'descripcion': 'Descripcion',
            'id_categoria_id': 'Categoria'
        }
        widgets = {
            'codigo':  forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Puede incluir hasta 100 caracteres'}),
            'marca': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese marca'}),
            'estado': forms.Select(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ingrese descripcion', 'rows': 3}),
            'id_categoria_id': forms.Select(attrs={'class': 'form-control'}),

        }


class ProductoEstadoForm(forms.ModelForm):

    class Meta:
        model = Producto

        fields = [
            'estado'
        ]
        labels = {
            'estado': 'Estado'
        }
        widgets = {
            'estado': forms.TextInput(attrs={'class': 'form-control'})

        }


class CategoriaForm(forms.ModelForm):

    class Meta:
        model = Categoria

        fields = [
            'nombre'
        ]
        labels = {
            'nombre': 'Nombre'
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese nombre'})
        }

src/mantenedor/views.py
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from .forms import *
from .models import *
from django.http import  HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from users.mixins import PermissionsRequiredMixin
from prestamos.models import Prestamos
# Create your views here.

#Producto
class ProductoList(PermissionsRequiredMixin, LoginRequiredMixin, ListView):
    model = Producto
    paginate_by = 10
    template_name = 'mantenedor/producto_list.html'
    required_permissions = ('mantenedor.add_producto',)

    def get_queryset(self):
        inner_qs = Prestamos.objects.filter(estado=1).values('id_producto_id')
        return Producto.objects.find(self.request.GET.get('q', False)).exclude(id__in=inner_qs).filter(estado=1).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context


class ProductoCreate(PermissionsRequiredMixin, LoginRequiredMixin, CreateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'mantenedor/producto_create.html'
    success_url = reverse_lazy('mantenedor:producto_listar')
    success_message = 'Producto creado exitosamente'
    required_permissions = ('mantenedor.add_producto',)


class ProductoUpdate(PermissionsRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'mantenedor/producto_update.html'
    success_url = reverse_lazy('mantenedor:producto_listar')
    required_permissions = ('mantenedor.change_producto',)


class ProductoEstado(PermissionsRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Producto
    form_class = ProductoEstadoForm
    template_name = 'mantenedor/cambiar_estado.html'
    success_url = reverse_lazy('mantenedor:producto_listar')
    required_permissions = ('mantenedor.change_producto',)


class ProductoDeBajaList(PermissionsRequiredMixin, LoginRequiredMixin, ListView):
    model = Producto
    template_name = 'mantenedor/productos_baja_list.html'
    required_permissions = ('prestamos.add_prestamo',)

    def get_queryset(self):
        return Producto.objects.find(self.request.GET.get('q', False)).filter(estado=0).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context


class ProductoMantencionList(PermissionsRequiredMixin, LoginRequiredMixin, ListView):
    model = Producto
    template_name = 'mantenedor/productos_mantencion_list.html'
    required_permissions = ('prestamos.add_prestamo',)

    def get_queryset(self):
        return Producto.objects.find(self.request.GET.get('q', False)).filter(estado=2).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context

# class ProductoDelete(PermissionsRequiredMixin, LoginRequiredMixin, DeleteView):
#     model = Producto
#     template_name = 'mantenedor/producto_delete.html'
#     success_url = reverse_lazy('mantenedor:producto_listar')
#     required_permissions = ('mantenedor.delete_producto',)

#Categoria
class CategoriaList(PermissionsRequiredMixin, LoginRequiredMixin, ListView):
    model = Categoria
    template_name = 'mantenedor/categoria_list.html'
    required_permissions = ('mantenedor.add_categoria',)


class CategoriaCreate(PermissionsRequiredMixin, LoginRequiredMixin, CreateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'mantenedor/categoria_create.html'
    success_url = reverse_lazy('mantenedor:categoria_listar')
    required_permissions = ('mantenedor.add_categoria',)


class CategoriaUpdate(PermissionsRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'mantenedor/categoria_update.html'
    success_url = reverse_lazy('mantenedor:categoria_listar')
    required_permissions = ('mantenedor.change_categoria',)


class CategoriaDelete(PermissionsRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Categoria
    template_name = 'mantenedor/categoria_delete.html'
    success_url = reverse_lazy('mantenedor:categoria_listar')
    required_permissions = ('mantenedor.delete_categoria')


def total_productos(request):

    obj = Producto.objects.filter(estado=1).order_by('-id')

    for abc in obj:
        obj_codigo = abc.codigo,
        obj_marcas = abc.marca,
        obj_descripcion = abc.descripcion,
        obj_categoria = abc.id_categoria_id

    context = {
        "obj": obj,
        "obj_codigo": obj_codigo,
        "obj_marcas": obj_marcas,
        "obj_descripcion": obj_descripcion,
        "obj_categoria": obj_categoria,

    }

    return render(request, "mantenedor/lista_productos.html", context)


def productos_disponibles(request):

    inner_qs3 = Prestamos.objects.filter(estado=1).values('id_producto_id')
    obj = Producto.objects.exclude(id__in=inner_qs3).filter(estado=1)

    for abc in obj:
        obj_codigo = abc.codigo,
        obj_marcas = abc.marca,
        obj_descripcion = abc.descripcion,
        obj_categoria = abc.id_categoria_id

    context = {

        "obj_codigo": obj_codigo,
        "obj_marcas": obj_marcas,
        "obj_descripcion": obj_descripcion,
        "obj_categoria": obj_categoria,
        "obj": obj,

    }

    return render(request, "mantenedor/total_productos.html", context)


def productos_mantencion(request):

    obj = Producto.objects.filter(estado=2)

    for abc in obj:
        obj_codigo = abc.codigo,
        obj_marcas = abc.marca,
        obj_descripcion = abc.descripcion,
        obj_categoria = abc.id_categoria_id,

    context = {
        "obj": obj,
        "obj_codigo": obj_codigo,
        "obj_marcas": obj_marcas,
        "obj_descripcion": obj_descripcion,
        "obj_categoria": obj_categoria,

    }

    return render(request, "mantenedor/productos_mantencion.html", context)


def productos_prestados(request):

    inner_qs = Prestamos.objects.filter(estado=1).values('id_producto_id')
    obj = Producto.objects.filter(id__in=inner_qs)

    for abc in obj:
        obj_codigo = abc.codigo,
        obj_marcas = abc.marca,
        obj_descripcion = abc.descripcion,
        obj_categoria = abc.id_categoria_id,

    context = {
        "obj": obj,
        "obj_codigo": obj_codigo,
        "obj_marcas": obj_marcas,
        "obj_descripcion": obj_descripcion,
        "obj_categoria": obj_categoria,

    }

    return render(request, "mantenedor/productos_prestados.html", context)


def productos_baja(request):

    obj = Producto.objects.filter(estado=0)

    for abc in obj:
        obj_codigo = abc.codigo,
        obj_marcas = abc.marca,
        obj_descripcion = abc.descripcion,
        obj_categoria = abc.id_categoria_id,

    context = {
        "obj": obj,
        "obj_codigo": obj_codigo,
        "obj_marcas": obj_marcas,
        "obj_descripcion": obj_descripcion,
        "obj_categoria": obj_categoria,

    }

    return render(request, "mantenedor/productos_baja.html", context)

src/mantenedor/templates/mantenedor/categoria_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Categoria-Registrar</title>
</head>
<body>
    {% extends 'base/base.html'%}

    {%block content%}

    <div class="col-sm-8">
        <h1>REGISTRO DE CATEGORIA</h1>
        <hr>
        <form method="POST" action="">
            {% csrf_token%}
            {{form.as_p}}
            <hr>
            <input type='submit' class="btn btn-primary" value='Guardar Registro'>

        </form>
    </div>


</body>
</html>
{%endblock%}

src/mantenedor/templates/mantenedor/categoria_delete.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Categoria-Eliminar</title>
  </head>
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de categoria "{{ categoria.nombre}}" ?</h3>
    <button class = "btn btn-danger" type="submit">Si, eliminar</button>
    <a class = "btn btn-default" href="{% url 'mantenedor:categoria_listar' %}">Cancelar</a>

</form>
</html>
{% endblock %}

src/mantenedor/templates/mantenedor/categoria_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Categoria-Listar</title>
</head>
{% extends 'base/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<div class="table-responsive"/>
	<h1>LISTA DE CATEGORIAS</h1>
	<hr>
	<table class="table table-bordered">
		<thead>
			<tr>
				<td>Nombre</td>
			</tr>
		</thead>
		<tbody>
			{% for categoria_list in object_list %}
			<tr>
				<td>{{categoria_list.nombre}}</td>
        <td style="border :1px solid transparent ">
					    <a class="btn btn-primary" href="{% url 'mantenedor:categoria_editar' categoria_list.id %}"><i class="ion-edit"></i> Editar</a>
              <a class="btn btn-danger" href="{% url 'mantenedor:categoria_eliminar' categoria_list.id %}"> <i class="ion-android-delete"></i> Eliminar</a>
        </td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<h1>No hay registros de categoria</h1>
	<hr>
	<td>
		<a class="btn btn-primary" href="{% url 'mantenedor:categoria_crear' %}"> <i class="ion-plus-round"></i> Agregar Registro </a>
	</td>
	{% endif %}
</div>
</div>
 </html>
{% endblock %}

src/mantenedor/templates/mantenedor/categoria_update.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Categoria-Editar</title>
  </head>
{% extends 'base/base.html'%}
{%block content%}
  <div class="row">
      <div class="col-xs-5">
          <h1>EDITAR CATEGORIA</h1>
          <form method="POST" action="">
              {% csrf_token%}
              {{form.as_p}}
              <hr>
              <input type='submit' class="btn btn-primary" value='Guardar Cambios'>
        </form>
      </div>
  </div>

  <br>
</html>
{%endblock%}

src/mantenedor/templates/mantenedor/lista_productos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--<h1>Lista de productos</h1>-->
{%for abc in obj%}
<div class="panel panel-info">

    <div class="panel-heading">
            <i class="fas fa-circle"></i> Código: {{abc.codigo}}</div>
    <ul class="list-group">
        <li class="list-group-item">Marca: {{abc.marca}}</li>
        <li class="list-group-item">Descripcion: {{abc.descripcion}}</li>
        <li class="list-group-item">Categoria: {{abc.id_categoria_id}}</li>
    </ul>

</div>
{%endfor%}
</body>
</html>

src/mantenedor/templates/mantenedor/producto_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Producto-Registrar</title>
</head>
<body>
    {% extends 'base/base.html'%}

    {%block content%}
    <div class="row">
        <div class="col-sm-8">
            <h1>REGISTRO DE PRODUCTO</h1>
            <hr>
            <form method="POST" action="">
                {% csrf_token%}
                {{form.as_p}}
                <input type='submit' class="btn btn-primary" value='Guardar Registro'>
            </form>
            <br>
        </div>
    </div>
</body>
</html>
{%endblock%}

src/mantenedor/templates/mantenedor/producto_delete.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Producto-Eliminar</title>
  </head>
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de producto "{{ producto.nombre}}" ?</h3>
    <button class = "btn btn-danger" type="submit">Si, eliminar</button>
    <a class = "btn btn-default" href="{% url 'mantenedor:producto_listar' %}">Cancelar</a>

</form>
</html>
{% endblock %}

src/mantenedor/templates/mantenedor/producto_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Producto-Listar</title>
</head>
{% extends 'base/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<h1>LISTA DE PRODUCTOS</h1>

	  <div class="search-form" class="col-md-4">
		<form id="search-form" action="" method="get">
		  <div class="input-group">
			<input type="text" name="q" class="form-control" value="{{ q }}" placeholder="Buscar: Código, Marca o Descripción" autofocus/>
			<span class="input-group-addon" onclick="document.getElementById('search-form').submit()">
			  <i class="fa fa-search"></i>
			</span>
		  </div>
		</form>
	  </div>

	<div class="table-responsive"/>
	<hr>
	<div class="alert alert-success" role="alert">
		Los productos que actualmente estan en <strong>"Prestamo"</strong> no apareceran en lista
	</div>
	<table class="table table-bordered">
		<thead>
		<tr>
			<td>Codigo</td>
			<td>Marca</td>
			<td>Categoria</td>
			<td>Descripcion</td>
		</tr>
		</thead>
		<tbody>
		{% for producto_list in object_list %}
		<tr>
			<td>{{producto_list.codigo}}</td>
			<td>{{producto_list.marca}}</td>
			<td>{{producto_list.id_categoria_id}}</td>
			<td>{{producto_list.descripcion}}</td>
			<td style="border :1px solid transparent ">
				<a class="btn btn-primary" href="{% url 'mantenedor:producto_editar' producto_list.id %}"><i class="ion-edit" data-toggle="tooltip" data-placement="top" title="Editar"></i></a>
              	<a class="btn btn-danger" href="{% url 'mantenedor:producto_estado' producto_list.id %}"> <i class="ion-android-delete" data-toggle="tooltip" data-placement="top" title="Eliminar"></i></a>
			</td>
		</tr>
		{% endfor %}
		</tbody>
	</table>



	{% else %}

	<div>
		<h1>Sin registros de productos o actualmente estan en mantención</h1>
		<hr>
		<td>
			<a class="btn btn-primary" href="{% url 'mantenedor:producto_crear' %}"> <i class="ion-plus-round"></i> Agregar Registro </a>
		</td>
		{% endif %}

	</div>
</div>
{% endblock %}
</html>

src/mantenedor/templates/mantenedor/producto_update.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Producto-Editar</title>
  </head>
{% extends 'base/base.html'%}
{%block content%}
  <div class="row">
      <div class="col-xs-5">
          <h1>EDITAR PRODUCTO</h1>
          <hr>
          <form method="POST" action="">
              {% csrf_token%}
              {{form.as_p}}
              <hr>
              <input type='submit' class="btn btn-primary" value='Guardar Cambios'>
            </form>
      </div>
  </div>
  <br>
</html>
{%endblock%}

src/mantenedor/templates/mantenedor/productos_baja.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--<h1>Lista de productos</h1>-->
{%for abc in obj%}
<div class="panel panel-danger">

    <div class="panel-heading">
            <i class="fas fa-circle"></i> Código: {{abc.codigo}}</div>
    <ul class="list-group">
        <li class="list-group-item">Marca: {{abc.marca}}</li>
        <li class="list-group-item">Descripcion: {{abc.descripcion}}</li>
        <li class="list-group-item">Categoria: {{abc.id_categoria_id}}</li>
    </ul>

</div>
{%endfor%}
</body>
</html>

src/mantenedor/templates/mantenedor/productos_baja_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Producto-Listar-Dados Baja</title>
</head>
{% extends 'base/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<h1>LISTA DE PRODUCTOS DADOS DE BAJA</h1>

	  <div class="search-form" class="col-md-4">
		<form id="search-form" action="" method="get">
		  <div class="input-group">
			<input type="text" name="q" class="form-control" value="{{ q }}" placeholder="Buscar: Código, Marca o Descripción" autofocus/>
			<span class="input-group-addon" onclick="document.getElementById('search-form').submit()">
			  <i class="fa fa-search"></i>
			</span>
		  </div>
		</form>
	  </div>

	<div class="table-responsive"/>
	<hr>

	<table class="table table-bordered">
		<thead>
		<tr>
			<td>Codigo</td>
			<td>Marca</td>
			<td>Categoria</td>
			<td>Descripcion</td>
		</tr>
		</thead>
		<tbody>
		{% for producto_list in object_list %}
		<tr>
			<td>{{producto_list.codigo}}</td>
			<td>{{producto_list.marca}}</td>
			<td>{{producto_list.id_categoria_id}}</td>
			<td>{{producto_list.descripcion}}</td>
			<td style="border :1px solid transparent ">
				<a class="btn btn-primary" href="{% url 'mantenedor:producto_editar' producto_list.id %}"><i class="ion-edit" data-toggle="tooltip" data-placement="top" title="Editar"></i></a>
			</td>
		</tr>
		{% endfor %}
		</tbody>
	</table>
	{% else %}
	<h1>Sin registros</h1>
	{% endif %}
</div>
</html>
</html>
{% endblock %}

src/mantenedor/templates/mantenedor/productos_mantencion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--<h1>Lista de productos</h1>-->
{%for abc in obj%}
<div class="panel panel-default">

    <div class="panel-heading">
            <i class="fas fa-circle"></i> Código: {{abc.codigo}}</div>
    <ul class="list-group">
        <li class="list-group-item">Marca: {{abc.marca}}</li>
        <li class="list-group-item">Descripcion: {{abc.descripcion}}</li>
        <li class="list-group-item">Categoria: {{abc.id_categoria_id}}</li>
    </ul>

</div>
{%endfor%}
</body>
</html>

src/mantenedor/templates/mantenedor/productos_mantencion_list.html
<!DOCTYPE html>
<ht lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Producto-Listar-En Mantencion</title>
</head>
{% extends 'base/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<h1>LISTA DE PRODUCTOS EN MANTENCIÓN</h1>

	  <div class="search-form" class="col-md-4">
		<form id="search-form" action="" method="get">
		  <div class="input-group">
			<input type="text" name="q" class="form-control" value="{{ q }}" placeholder="Buscar: Código, Marca o Descripción" autofocus/>
			<span class="input-group-addon" onclick="document.getElementById('search-form').submit()">
			  <i class="fa fa-search"></i>
			</span>
		  </div>
		</form>
	  </div>

	<div class="table-responsive"/>
	<hr>

	<table class="table table-bordered">
		<thead>
		<tr>
			<td>Codigo</td>
			<td>Marca</td>
			<td>Categoria</td>
			<td>Descripcion</td>
		</tr>
		</thead>
		<tbody>
		{% for producto_list in object_list %}
		<tr>
			<td>{{producto_list.codigo}}</td>
			<td>{{producto_list.marca}}</td>
			<td>{{producto_list.id_categoria_id}}</td>
			<td>{{producto_list.descripcion}}</td>
			<td style="border :1px solid transparent ">
				<a class="btn btn-primary" href="{% url 'mantenedor:producto_editar' producto_list.id %}"><i class="ion-edit" data-toggle="tooltip" data-placement="top" title="Editar"></i></a>
			</td>
		</tr>
		{% endfor %}
		</tbody>
	</table>
	{% else %}
	<h1>Sin registros</h1>
	{% endif %}
</div>
</div>
</html>
{% endblock %}

src/mantenedor/templates/mantenedor/productos_prestados.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--<h1>Lista de productos</h1>-->
{%for abc in obj%}
<div class="panel panel-primary">

    <div class="panel-heading">
            <i class="fas fa-circle"></i> Código: {{abc.codigo}}</div>
    <ul class="list-group">
        <li class="list-group-item">Marca: {{abc.marca}}</li>
        <li class="list-group-item">Descripcion: {{abc.descripcion}}</li>
        <li class="list-group-item">Categoria: {{abc.id_categoria_id}}</li>
    </ul>

</div>
{%endfor%}
</body>
</html>