src/home/urls.py
from django.conf.urls import url
from .views import HomeTemplateView, dashboard, usuarios

# urlpatterns = [
#     url(r'^$', views.Dashboard, name='index'),
#     #url(r'^$', HomeTemplateView.as_view(), name='index'),
# ]

urlpatterns = [
    url(r'^$', HomeTemplateView.as_view(), name='index'),
    url(r'^dashboard$', dashboard, name='dashboard'),
    url(r'^usuarios$', usuarios, name='usuarios'),

]

src/prestamo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    #modelwidget
    url(r'^select2/', include('django_select2.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('users.urls', namespace='usuario')),

    #URL de mantenedor

    url(r'^', include('mantenedor.urls', namespace="mantenedor")),

    #Url de Prestamos

    url(r'^', include('prestamos.urls', namespace="prestamos")),

    #Url de Laboratorio

    url(r'^laboratorio/', include('laboratorio.urls', namespace="laboratorio")),

    #Url de Reportes

    url(r'^reportes/', include('reportes.urls', namespace="reportes")),

    # URL del Home

    url(r'^', include('home.urls', namespace='home')),

    # URL Cuentas de usuario

    url(r'^accounts/', include('allauth.urls')),

    # urls de login y de recuperacion de contraseña

    url(r'^password/reset/', password_reset,
        {'template_name': 'account/password_reset_email_form.html',
         'email_template_name': 'account/password_reset_email.html'},
        name='password_reset'),

    url(r'^password/reset-done', password_reset_done,
        {'template_name': 'account/password_reset_email_done.html'},
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'account/password_reset_email_confirm.html'},
        name='password_reset_confirm'),

    url(r'^reset/done', password_reset_complete,
        {'template_name': 'account/password_reset_email_complete.html'},
        name='password_reset_complete'),

]

src/prestamos/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .models import *
from .views import *
from prestamos import views
#Prestamo

urlpatterns = [
    url(r'^prestamos/listar/prestamo$', PrestamoList.as_view(), name='prestamo_listar'),
    #url(r'^prestamos/crear/prestamo$', views.user, name='prestamo_crear_prestamo'),
    url(r'^prestamos/editar/prestamo/(?P<pk>\d+)/$', PrestamoUpdate.as_view(), name='prestamo_editar'),
    url(r'^prestamos/eliminar/prestamo/(?P<pk>\d+)/$', PrestamoDelete.as_view(), name='prestamo_eliminar'),
    url(r'^prestamos/crear/prestamos$', PrestamoCreate.as_view(), name='prestamo_crear'),
    url(r'^prestamos/devolucion/(?P<pk>\d+)/$', Devolucion.as_view(), name='devolucion'),
    url(r'^prestamos/listar/devoluciones$', DevolucionList.as_view(), name='devolucion_listar'),
    url(r'^prestamos/listar/retrasos$', RetrasosList.as_view(), name='retrasos'),
    url(r'^prestamos/listar/danos$', DanosList.as_view(), name='danos'),

    url(r'^prestamos/listar/prestamo/dialog1$', views.prestamo_activo, name='list_prestamos'),
    url(r'^prestamos/listar/prestamo/dialog2$', views.prestamo_atrasado, name='list_prestamos_atrasados'),
]

src/prestamos/models.py
from django.db import models
from mantenedor.models import Producto
from django.contrib.auth.models import User
from django.db.models import Q

# Create your models here.


class PrestamoManager(models.Manager):

    def find(self, search):
        if not search:
            return self

        qs = Q(id_usuario__username__icontains=search) | \
             Q(id_producto__codigo__icontains=search)

        return self.filter(qs)


class Prestamos(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    id_usuario = models.ForeignKey(User)
    id_producto = models.ForeignKey('mantenedor.Producto')
    estado = models.CharField(max_length=100, default=1, choices=(('1', 'Activo'), ('0', 'Inactivo')))
    fecha_prestamo = models.DateTimeField()
    fecha_devolucion = models.DateTimeField()
    observaciones = models.CharField(max_length=200)
    fecha_actual = models.DateTimeField(auto_now_add=True, auto_now=False)
    estado_entrega = models.CharField(max_length=200, default="", choices=(('1', 'Sin Detalles'), ('0', 'Con Detalles')))
    observaciones_devolucion = models.CharField(max_length=200)

    objects = PrestamoManager()

    def __str__(self):
        return self.observaciones

src/prestamos/forms.py
from .models import *
from django import forms
from datetimewidget.widgets import DateTimeWidget
from .fields import UserSelectWidget
from django_select2.forms import Select2Widget
from django.contrib.auth.models import User
from mantenedor.models import Producto
from django.forms import ModelChoiceField


class PrestamoForm(forms.ModelForm):
    inner_qs = Prestamos.objects.filter(estado=1).values('id_producto_id')
    id_producto = forms.ModelChoiceField(queryset=Producto.objects.exclude(id__in=inner_qs).filter(estado=1), label='Producto')

    class Meta:
        model = Prestamos
        exclude = ['fecha_actual', 'estado_entrega', 'observaciones_devolucion']

        fields = [
            'id_usuario',
            'id_producto',
            'estado',
            'fecha_prestamo',
            'fecha_devolucion',
            'observaciones',
        ]
        labels = {
            'id_usuario': 'Usuario',
            'id_producto': 'Producto',
            'estado': 'Estado',
            'fecha_prestamo': 'Fecha Prestamo',
            'fecha_devolucion': 'Fecha Devolucion',
            'observaciones': 'Observaciones',
        }

        widgets = {
            'id_usuario': forms.Select(attrs={'class': 'form-control', 'id': 'usuario'}),
            'id_producto': forms.Select(attrs={'class': 'form-control', 'id': 'productos'}),
            'estado': forms.Select(attrs={'class': 'form-control', 'id': 'estadoPrestamo'}),
            'fecha_prestamo': DateTimeWidget(attrs={'id': "fecha_prestamo"}, usel10n=True, bootstrap_version=3),
            'fecha_devolucion': DateTimeWidget(attrs={'id': "fecha_devolucion"}, usel10n=True, bootstrap_version=3),
            'observaciones': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ingrese Observacion', 'rows': 3}),
        }


class PrestamoEditForm(forms.ModelForm):

    class Meta:
        model = Prestamos
        exclude = ['id_usuario', 'id_producto', 'estado']

        fields = [
            'fecha_prestamo',
            'fecha_devolucion',
            'observaciones',
        ]
        labels = {
            'fecha_prestamo': 'Fecha Prestamo',
            'fecha_devolucion': 'Fecha Devolucion',
            'observaciones': 'Observaciones',
        }

        widgets = {
            'fecha_prestamo': DateTimeWidget(attrs={'id': "fecha_prestamo"}, usel10n=True, bootstrap_version=3),
            'fecha_devolucion': DateTimeWidget(attrs={'id': "fecha_devolucion"}, usel10n=True, bootstrap_version=3),
            'observaciones': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ingrese Observacion', 'rows': 3}),
        }


class DevolucionForm(forms.ModelForm):

    class Meta:
        model = Prestamos
        exclude = ['id_usuario', 'id_producto', 'fecha_prestamo', 'fecha_devolucion', 'observaciones']

        fields = [
            #'fecha_actual',
            'estado',
            'estado_entrega',
            'observaciones_devolucion'
        ]
        labels = {
            'estado': 'Estado de Prestamo',
            #'fecha_actual': 'Fecha Actual',
            'estado_entrega': 'Estado Devolucion',
            'observaciones_devolucion': 'Observaciones al Prestamo'
        }

        widgets = {
            #'fecha_actual': DateTimeWidget(attrs={'id': "fecha_prestamo"}, usel10n=True, bootstrap_version=3),
            'estado': forms.Select(attrs={'class': 'form-control', 'autofocus': 'autofocus', 'id': 'estado'}),
            'estado_entrega': forms.Select(attrs={'class': 'form-control'}),
            'observaciones_devolucion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ingrese Observacion', 'rows': 3}),
        }

src/prestamos/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .forms import *
from .models import *

from django.contrib.auth.mixins import LoginRequiredMixin
from users.mixins import PermissionsRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from datetime import datetime
from django.db.models import F

#Prestamo
class PrestamoList(PermissionsRequiredMixin, LoginRequiredMixin, ListView):
    model = Prestamos
    template_name = 'prestamos/prestamos_list.html'
    required_permissions = ('prestamos.add_prestamo',)

    def get_queryset(self):
        return Prestamos.objects.find(self.request.GET.get('q', False)).filter(estado=1).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context


class PrestamoCreate(PermissionsRequiredMixin, LoginRequiredMixin, CreateView):
    model = Prestamos
    form_class = PrestamoForm
    template_name = 'prestamos/prestamos_create.html'
    success_url = reverse_lazy('prestamos:prestamo_listar')
    required_permissions = ('prestamos.add_prestamo',)


class PrestamoUpdate(PermissionsRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Prestamos
    form_class = PrestamoEditForm
    template_name = 'prestamos/prestamos_update.html'
    success_url = reverse_lazy('prestamos:prestamo_listar')
    required_permissions = ('prestamos.change_prestamo',)


class PrestamoDelete(PermissionsRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Prestamos
    template_name = 'prestamos/prestamos_delete.html'
    success_url = reverse_lazy('prestamos:prestamo_listar')
    required_permissions = ('prestamos.delete_prestamo',)


class Devolucion(PermissionsRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Prestamos
    form_class = DevolucionForm
    template_name = 'prestamos/devoluciones.html'
    success_url = reverse_lazy('prestamos:prestamo_listar')
    required_permissions = ('prestamos.change_prestamo',)


class DevolucionList(PermissionsRequiredMixin, LoginRequiredMixin, ListView):
    model = Prestamos
    template_name = 'prestamos/devoluciones_list.html'
    required_permissions = ('prestamos.add_prestamo',)

    # def get_queryset(self, *args, **kwargs):
    #     return Prestamos.objects.filter(estado=0).order_by('-id')
    def get_queryset(self):
        return Prestamos.objects.find(self.request.GET.get('q', False)).filter(estado=0).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q', '')
        return context


class RetrasosList(PermissionsRequiredMixin, LoginRequiredMixin, ListView):
    model = Prestamos
    template_name = 'prestamos/retrasos.html'
    required_permissions = ('prestamos.add_prestamo',)

    def get_queryset(self):
        return Prestamos.objects.filter(fecha_devolucion__lt=F('fecha_actual')).order_by('-id')
        #return Prestamos.objects.filter(fecha_devolucion__lt='2018-06-27 02:00:35-04').order_by('-id')


class DanosList(PermissionsRequiredMixin, LoginRequiredMixin, ListView):
    model = Prestamos
    template_name = 'prestamos/danos.html'
    required_permissions = ('prestamos.add_prestamo',)

    def get_queryset(self):
        return Prestamos.objects.filter(estado_entrega=0).order_by('-id')


def prestamo_activo(request):

    obj = Prestamos.objects.filter(estado=1).order_by('-id')

    for abc in obj:
        obj_usuario = abc.id_usuario,
        obj_producto = abc.id_producto,
        obj_fechaDevol = abc.fecha_devolucion,

    context = {
        "obj": obj,
        "obj_usuario": obj_usuario,
        "obj_producto": obj_producto,
        "obj_fechaDevol": obj_fechaDevol,
    }

    return render(request, "prestamos/list_prestamos.html", context)


def prestamo_atrasado(request):

    obj = Prestamos.objects.filter(fecha_devolucion__lte=datetime.now(), estado=1).order_by('-id')
    for abc in obj:
        obj_usuario = abc.id_usuario,
        obj_producto = abc.id_producto,
        obj_fechaDevol = abc.fecha_devolucion,

    context = {
        "obj": obj,
        "obj_usuario": obj_usuario,
        "obj_producto": obj_producto,
        "obj_fechaDevol": obj_fechaDevol,

    }

    return render(request, "prestamos/list_prestamos_atrasado.html", context)

src/prestamos/templates/prestamos/danos.html
<!DOCTYPE html>
<div lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Prestamo-Listar Devoluciones Daños</title>
</head>
{% extends 'base/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<div class="table-responsive"/>
	<h1>LISTA DE DEVOLUCIONES CON DAÑOS</h1>
	<hr>

	<!--<div class="search-form" class="col-md-4">-->
		<!--<form id="search-form" action="" method="get">-->
		  <!--<div class="input-group">-->
			<!--<input type="text" name="q" class="form-control" value="{{ q }}" placeholder="Buscar: Usuarios o Codigo PC" autofocus/>-->
			<!--<span class="input-group-addon" onclick="document.getElementById('search-form').submit()">-->
			  <!--<i class="fas fa-search"></i>-->
			<!--</span>-->
		  <!--</div>-->
		<!--</form>-->
	  <!--</div>-->
	<!--<hr>-->
	<table class="table table-striped">
		<thead>
			<tr>
				<td><strong>Usuario</strong></td>
				<td><strong>Producto</strong></td>
				<td><strong>Fecha Prestamo</strong></td>
				<td><strong>Fecha Devolucion</strong></td>
				<td><strong>Observaciones de Prestamo</strong></td>
				<td><strong>Observaciones de Devolucion</strong></td>
			</tr>
		</thead>
		<tbody>
			{% for prestamos_list in object_list %}
			<tr>
				<td>{{prestamos_list.id_usuario}}</td>
				<td>{{prestamos_list.id_producto}}</td>
				<td>{{prestamos_list.fecha_prestamo}}</td>
				<td>{{prestamos_list.fecha_devolucion}}</td>
				<td>{{prestamos_list.observaciones}}</td>
				<td>{{prestamos_list.observaciones_devolucion}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<h1>Sin registros</h1>
	<hr>
	{% endif %}
</div>
</div>
</html>
{% endblock %}

src/prestamos/templates/prestamos/devoluciones.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Prestamo-Editar</title>
  </head>
{% extends 'base/base.html'%}
{%block content%}
  <div class="row">
      <div class="col-xs-5">
          <h1>GENERAR DEVOLUCIÓN</h1>
          <div class="alert alert-danger" role="alert">
              Para generar devolucion el estado debe estar <strong>"Inactivo"</strong>, si la devolución
              presenta detalles debe añadir una observacion.
          </div>

          <form method="POST" action="">
              {% csrf_token%}
              {{form.as_p}}
              <hr>

                <input id="validate" class="btn btn-primary" value='Realizar Devolucion'>

        </form>
      </div>
  </div>

  <script>
  function ok(){
	alertify.success("Este prestamo fue guardado en <b>HISTORIAL DEVOLUCIONES.</b></a>");
	return false;
  }

  function alerta() {
      alertify.error("El estado debe quedar <strong>\"Inactivo\"</strong>");
  }
    $('#validate').click(function() {
        var estado = document.getElementById("estado");
        var seleccion = estado.options[estado.selectedIndex].text;
        if (seleccion === "Activo") {
            alerta();
            document.getElementById("estado").focus();
        } else {
            this.form.submit();
            ok();
        }
    });

</script>

  <br>
</html>
{%endblock%}

src/prestamos/templates/prestamos/devoluciones_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Prestamo-Listar</title>
</head>
{% extends 'base/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<div class="table-responsive"/>
	<h1>LISTA DE DEVOLUCIONES</h1>
	<hr>

	<div class="search-form" class="col-md-4">
		<form id="search-form" action="" method="get">
		  <div class="input-group">
			<input type="text" name="q" class="form-control" value="{{ q }}" placeholder="Buscar: Usuarios o Codigo PC" autofocus/>
			<span class="input-group-addon" onclick="document.getElementById('search-form').submit()">
			  <i class="fas fa-search"></i>
			</span>
		  </div>
		</form>
	  </div>
	<hr>
	<table class="table table-hover">
		<thead>
			<tr>
				<td>Usuario</td>
				<td>Producto</td>
				<td>Fecha Prestamo</td>
				<td>Fecha Devolucion</td>
			</tr>
		</thead>
		<tbody>
			{% for prestamos_list in object_list %}
			<tr>
				<td>{{prestamos_list.id_usuario}}</td>
				<td>{{prestamos_list.id_producto}}</td>
				<td>{{prestamos_list.fecha_prestamo}}</td>
				<td>{{prestamos_list.fecha_devolucion}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<h1>No hay registros de devoluciones</h1>
	<hr>
	<!--<td>-->
		<!--<a class="btn btn-primary" href="{% url 'prestamos:prestamo_crear' %}"> <i class="ion-plus-round"></i> Agregar Registro </a>-->
	<!--</td>-->
	{% endif %}
</div>
</div>
 </html>
{% endblock %}

src/prestamos/templates/prestamos/list_prestamos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--<h1>Lista de productos</h1>-->
{%for abc in obj%}
<div class="panel panel-primary">

    <div class="panel-heading">
            <i class="fas fa-circle"></i> Usuario: {{abc.id_usuario.username}}</div>
    <ul class="list-group">
        <li class="list-group-item">Producto: {{abc.id_producto}}</li>
        <li class="list-group-item">Fecha Devolucion: {{abc.fecha_devolucion}}</li>
    </ul>

</div>
{%endfor%}
</body>
</html>

src/prestamos/templates/prestamos/list_prestamos_atrasado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--<h1>Lista de productos</h1>-->
{%for abc in obj%}
<div class="panel panel-danger">

    <div class="panel-heading">
            <i class="fas fa-circle"></i> Usuario: {{abc.id_usuario.username}}</div>
    <ul class="list-group">
        <li class="list-group-item">Producto: {{abc.id_producto}}</li>
        <li class="list-group-item">Fecha Devolucion: {{abc.fecha_devolucion}}</li>
    </ul>

</div>
{%endfor%}
</body>
</html>

src/prestamos/templates/prestamos/prestamos_create.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <title>Sistema Prestamos | Prestamos-Registrar</title>

</head>
    {% extends 'base/base.html' %}
<body>
{%block content%}
    <div class="row">
        <div class="col-sm-8">
            <h1>REGISTRO DE PRESTAMOS</h1>
            <form method="POST" action="">
                    {% csrf_token%}
                    {{form.as_p}}
                    <input id="validar" class="btn btn-primary" value='Realizar Prestamo'>
            </form>
            <br>
        </div>
    </div>

<script>
    function alerta() {
        alertify.error("El estado debe quedar <strong>\"Activo\"</strong>");
    }

    $('#validar').click(function() {
        var estado = document.getElementById("estadoPrestamo");
        var seleccion = estado.options[estado.selectedIndex].text;
        if (seleccion === "Inactivo") {
            alerta();
            document.getElementById("estadoPrestamo").focus();
        } else {
            this.form.submit();
        }
    });
</script>
</body>
</html>
{%endblock%}

src/prestamos/templates/prestamos/prestamos_delete.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Prestamo-Eliminar</title>
  </head>
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro del producto"{{ prestamo.id_producto}}" ?</h3>
    <button class = "btn btn-danger" type="submit">Si, eliminar</button>
    <a class = "btn btn-default" href="{% url 'prestamos:prestamo_listar' %}">Cancelar</a>

</form>
</html>
{% endblock %}

src/prestamos/templates/prestamos/prestamos_list.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Prestamo-Listar</title>
</head>
{% extends 'base/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<div class="table-responsive"/>
	<h1>LISTA DE PRESTAMOS</h1>
	<hr>

	<div class="search-form" class="col-md-4">
		<form id="search-form" action="" method="get">
		  <div class="input-group">
			<input type="text" name="q" class="form-control" value="{{ q }}" placeholder="Buscar: Usuarios" autofocus/>
			<span class="input-group-addon" onclick="document.getElementById('search-form').submit()">
			  <i class="fas fa-search"></i>
			</span>
		  </div>
		</form>
	  </div>
	<hr>
	<!--<h3>Estados de Prestamo: 1 = Activo | 0 = Inactivo</h3>-->
	<table class="table table-bordered">
		<thead>
			<tr>
				<!--<td>Estado</td>-->
				<td>Usuario</td>
				<td>Producto</td>
				<td>Fecha Prestamo</td>
				<td>Fecha Devolucion</td>
				<td>Observaciones</td>
			</tr>
		</thead>
		<tbody>
			{% for prestamos_list in object_list %}
			<tr>
				<!--<td>{{prestamos_list.estado}}</td>-->
				<td>{{prestamos_list.id_usuario}}</td>
				<td>{{prestamos_list.id_producto}}</td>
				<td>{{prestamos_list.fecha_prestamo}}</td>
				<td>{{prestamos_list.fecha_devolucion}}</td>
				<td>{{prestamos_list.observaciones}}</td>

			<!--{% if prestamos_list.estado == '1' %}-->
        <td style="border :1px solid transparent ">
			<a class="btn btn-primary" href="{% url 'prestamos:prestamo_editar' prestamos_list.id %}"><i class="ion-edit" data-toggle="tooltip" data-placement="top" title="Editar"></i> </a>
			<a class="btn btn-success" href="{% url 'prestamos:devolucion' prestamos_list.id %}"><i class="fas fa-undo-alt" data-toggle="tooltip" data-placement="top" title="Devolucion"></i> </a>
		</td>
			<!--{% else %}-->
		<!--<td style="border :1px solid transparent ">-->
			<!--<a class="btn btn-danger" href="{% url 'prestamos:prestamo_eliminar' prestamos_list.id %}"> <i class="ion-android-delete" data-toggle="tooltip" data-placement="top" title="Eliminar"></i> </a>-->
        <!--</td>-->
			<!--</tr>-->
			<!--{% endif %}-->
			{% endfor %}

		<script>
			$(function () {
				$('[data-toggle="tooltip"]').tooltip()
            })
		</script>

		</tbody>
	</table>
	{% else %}
	<h1>No hay registros de prestamos</h1>
	<hr>
	<td>
		<a class="btn btn-primary" href="{% url 'prestamos:prestamo_crear' %}"> <i class="ion-plus-round"></i> Agregar Registro </a>
	</td>
	{% endif %}
</div>
</div>
</html>
{% endblock %}

src/prestamos/templates/prestamos/prestamos_update.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Prestamo-Editar</title>
  </head>
{% extends 'base/base.html'%}
{%block content%}
  <div class="row">
      <div class="col-xs-5">
          <h1>EDITAR PRESTAMO</h1>
          <form method="POST" action="">
              {% csrf_token%}
              {{form.as_p}}
              <hr>
              <input type='submit' class="btn btn-primary" value='Guardar Cambios'>
        </form>
      </div>
  </div>

  <br>
</html>
{%endblock%}

src/prestamos/templates/prestamos/retrasos.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sistema Prestamos | Prestamo-Listar</title>
</head>
{% extends 'base/base.html' %}
{% block content %}
<div id="" class="gray-bg"><br>
	{% if object_list %}
	<div class="table-responsive"/>
	<h1>LISTA DE DEVOLUCIONES ATRASADAS</h1>
	<hr>

	<div class="search-form" class="col-md-4">
		<form id="search-form" action="" method="get">
		  <div class="input-group">
			<input type="text" name="q" class="form-control" value="{{ q }}" placeholder="Buscar: Usuarios o Codigo PC" autofocus/>
			<span class="input-group-addon" onclick="document.getElementById('search-form').submit()">
			  <i class="fas fa-search"></i>
			</span>
		  </div>
		</form>
	  </div>
	<hr>
	<table class="table table-striped">
		<thead>
			<tr>
				<td><strong>Usuario</strong></td>
				<td><strong>Producto</strong></td>
				<td><strong>Fecha Prestamo</strong></td>
				<td><strong>Fecha Devolucion</strong></td>
				<td><strong>Fecha Real Devolucion</strong></td>
			</tr>
		</thead>
		<tbody>
			{% for prestamos_list in object_list %}
			<tr>
				<td>{{prestamos_list.id_usuario}}</td>
				<td>{{prestamos_list.id_producto}}</td>
				<td>{{prestamos_list.fecha_prestamo}}</td>
				<td>{{prestamos_list.fecha_devolucion}}</td>
				<td>{{prestamos_list.fecha_actual}}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<h1>No hay registros de devoluciones</h1>
	<hr>
	<!--<td>-->
		<!--<a class="btn btn-primary" href="{% url 'prestamos:prestamo_crear' %}"> <i class="ion-plus-round"></i> Agregar Registro </a>-->
	<!--</td>-->
	{% endif %}
</div>
</div>
 </html>
{% endblock %}