src/home/urls.py
from django.conf.urls import url
from .views import HomeTemplateView, dashboard, usuarios

# urlpatterns = [
#     url(r'^$', views.Dashboard, name='index'),
#     #url(r'^$', HomeTemplateView.as_view(), name='index'),
# ]

urlpatterns = [
    url(r'^$', HomeTemplateView.as_view(), name='index'),
    url(r'^dashboard$', dashboard, name='dashboard'),
    url(r'^usuarios$', usuarios, name='usuarios'),

]

src/prestamo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    #modelwidget
    url(r'^select2/', include('django_select2.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('users.urls', namespace='usuario')),

    #URL de mantenedor

    url(r'^', include('mantenedor.urls', namespace="mantenedor")),

    #Url de Prestamos

    url(r'^', include('prestamos.urls', namespace="prestamos")),

    #Url de Laboratorio

    url(r'^laboratorio/', include('laboratorio.urls', namespace="laboratorio")),

    #Url de Reportes

    url(r'^reportes/', include('reportes.urls', namespace="reportes")),

    # URL del Home

    url(r'^', include('home.urls', namespace='home')),

    # URL Cuentas de usuario

    url(r'^accounts/', include('allauth.urls')),

    # urls de login y de recuperacion de contraseña

    url(r'^password/reset/', password_reset,
        {'template_name': 'account/password_reset_email_form.html',
         'email_template_name': 'account/password_reset_email.html'},
        name='password_reset'),

    url(r'^password/reset-done', password_reset_done,
        {'template_name': 'account/password_reset_email_done.html'},
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
        {'template_name': 'account/password_reset_email_confirm.html'},
        name='password_reset_confirm'),

    url(r'^reset/done', password_reset_complete,
        {'template_name': 'account/password_reset_email_complete.html'},
        name='password_reset_complete'),

]

src/reportes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *
from reportes import views


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='hom'),
    url(r'^report$', Reporte.as_view(), name='report'),
    url(r'^report/activo$', ReporteActivo.as_view(), name='report_activo'),
    url(r'^api/data/', get_data, name='api-data'),
    url(r'^api/chart/data/', ChartData.as_view()),
    #url(r'^reportes/pdf$', views.report_pdf, name='pdf'),
]

src/reportes/models.py
from django.db import models

# Create your models here.

src/reportes/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import View

from rest_framework.views import APIView
from rest_framework.views import Response

from django.contrib.auth import get_user_model

from prestamos.models import Prestamos
from mantenedor.models import Producto

from django.core.urlresolvers import reverse_lazy
from reportlab.platypus import TableStyle, Table, Spacer, Paragraph, Image
from reportlab.lib import colors
from reportlab.lib.units import cm
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4, cm
from django.views.generic import View
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from django.db.models import Avg, Max, Min, Sum, Count
from django.http import HttpResponse



# Create your views here.


User = get_user_model()

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'reportes/charts.html', {"customers": 10})


def get_data(request, *args, **kwargs):
    data = {
        "sales": 100,
        "customers": 10,
    }
    return JsonResponse(data)


class ChartData(APIView):
    authentication_classes = []
    permission_clases = []

    def get(self, request, format=None):
        #qs_count1 =User.objects.all().count()
        #qs_count2 = Prestamos.objects.all().count()
        inner_qs = Prestamos.objects.filter(estado=1).values('id_producto_id')
        pro_dis = Producto.objects.exclude(id__in=inner_qs).filter(estado=1).count()
        pro_ocu = Producto.objects.filter(id__in=inner_qs, estado=1).count()
        # inner = Prestamos.objects.values('id_producto_id')
        # inner2 = Producto.objects.values('id')
        # inner3 = Producto.objects.values('codigo')
        # total = Producto.objects.values('codigo', inner).count()
        # variable = Producto.objects.values('codigo', inner).count().filter(inner=inner2).annotate(inner, inner3).order_by(total)[:1]

        # var1 = Prestamos.objects.values('id_producto_id__codigo')
        # inner = var1.Count('id_producto_id').latest()
        # #inner = v.latest('max')

        labels = ["Productos Disponibles", "Productos En Prestamos"]
        default_items = [pro_dis, pro_ocu]
        data = {
                "labels": labels,
                "default": default_items
        }
        return Response(data)


class Reporte(View):

    def cabecera(self, pdf):
        #imagen = settings.MEDIA_ROOT+'link de la imagen.jpg'
        #pdf.drawImage(imagen, 40, 520, 120, 90, preserveAspectRatio=True)
        pdf.setFont("Helvetica", 16)
        pdf.drawString(300, 550, u"REPORTE DE PRESTAMO")
        pdf.setFont("Helvetica", 10)
        #pdf.drawString(200, 770, u"")

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='application/pdf')
        #response['Content-Disposition']='attachment; filename="%s"'
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer)
        self.cabecera(pdf)
        y = 420
        self.tabla(pdf, y)
        pdf.showPage()
        pdf.setLineWidth(0.1)
        pdf.save()
        pdf = buffer.getvalue()
        buffer.close()
        response.write(pdf)
        return response

    def tabla(self, pdf, y):
        encabezados = ('Nombre del Docente', 'Nombre Equipo', 'Fecha Prestamo', 'Fecha Devolucion Prestamo', 'Detalle')

        detalles = [(Prestamos.id_usuario, Prestamos.id_producto, Prestamos.fecha_prestamo, Prestamos.fecha_devolucion, Prestamos.observaciones)
                    for Prestamos in Prestamos.objects.all()]
        detalle_orden = Table([encabezados] + detalles, colWidths=[3* cm, 2* cm, 5* cm, 5* cm, 10* cm])
        detalle_orden.setStyle(TableStyle(
            [
            ('ALIGN',(0,0),(1,0),'CENTER'),
            ('GRID', (0, 0), (8, -1), 0.5, colors.darkgrey),
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
        ]
        ))
        detalle_orden.wrapOn(pdf, 800, 600)
        detalle_orden.drawOn(pdf, 40, -100)
        pdf.setPageSize(landscape(letter))

    template_name = 'reportes/reportes_prestamo.html'
    success_url = reverse_lazy('reportes:hom')


class ReporteActivo(View):

    def cabecera(self, pdf):
        #imagen = settings.MEDIA_ROOT+'link de la imagen.jpg'
        #pdf.drawImage(imagen, 40, 520, 120, 90, preserveAspectRatio=True)
        pdf.setFont("Helvetica", 16)
        pdf.drawString(180, 550, u"REPORTE DE PRESTAMOS ACTIVOS")
        pdf.setFont("Helvetica", 10)
        #pdf.drawString(200, 770, u"")

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type='application/pdf')
        #response['Content-Disposition']='attachment; filename="%s"'
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer)
        self.cabecera(pdf)
        y = 600
        self.tabla(pdf, y)
        pdf.showPage()
        pdf.setLineWidth(0.1)
        pdf.save()
        pdf = buffer.getvalue()
        buffer.close()
        response.write(pdf)
        return response

    def tabla(self, pdf, y):
        encabezados = ('Nombre del Docente', 'Nombre Equipo', 'Fecha Prestamo', 'Fecha Devolucion Prestamo', 'Detalle')

        detalles = [(Prestamos.id_usuario, Prestamos.id_producto, Prestamos.fecha_prestamo, Prestamos.fecha_devolucion, Prestamos.observaciones)
                    for Prestamos in Prestamos.objects.filter(estado=1)]
        detalle_orden = Table([encabezados] + detalles, colWidths=[3* cm, 2* cm, 5* cm, 5* cm, 10* cm])
        detalle_orden.setStyle(TableStyle(
            [
            ('ALIGN',(0,0),(1,0),'CENTER'),
            ('GRID', (0, 0), (8, -1), 0.5, colors.darkgrey),
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
        ]
        ))
        detalle_orden.wrapOn(pdf, 800, 600)
        detalle_orden.drawOn(pdf, 40, 450)
        pdf.setPageSize(landscape(letter))

    template_name = 'reportes/prestamos_activos.html'
    success_url = reverse_lazy('reportes:hom')

# def report_pdf(request):
#     #create the httpresponse headers with pdf
#     response = HttpResponse(content_type='application/pdf')
#     response['Content-Disposition'] = 'attachment; filename=report.pdf'
#     #create the pdf object, using the ByteIO as its file
#     buffer = BytesIO()
#     c = canvas.Canvas(buffer, pagesize=A4)
#
#     #header
#     c.setLineWidth(.3)
#     c.setFont('Helvetica', 22)
#     c.drawString(30, 750, 'Platzi')
#     c.setFont('Helvetica', 12)
#     c.drawString(30, 735, 'Report')
#
#     c.setFont('Helvetica-Bold', 12)
#     c.drawString(480, 750, '01/07/2018')
#     #start x, heigth end y, heigth
#     c.line(480, 747, 560, 747)
#
#     # Table header
#     styles = getSampleStyleSheet()
#     styleBH = styles["Normal"]
#     styleBH.aligment = TA_CENTER
#     styleBH.fontSize = 10
#
#     numero = Paragraph('''No.''', styleBH)
#     alumno = Paragraph('''Alumno''', styleBH)
#     b1 = Paragraph('''BIM1''', styleBH)
#     b2 = Paragraph('''BIM2''', styleBH)
#     b3 = Paragraph('''BIM3''', styleBH)
#     total = Paragraph('''TOTAL''', styleBH)
#     data = [(numero, alumno, b1, b2, b3, total)]
#
#     # Students table
#     students = [{'#': '1', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '2', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '3', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '4', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '5', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '6', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '7', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '8', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '9', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '10', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '2', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '3', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '4', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '5', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '6', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '7', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '8', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '9', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '10', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '2', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '3', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '4', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '5', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '6', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},
#                 {'#': '7', 'Name': 'Gonzalo', 'b1': '3.4', 'b2': '2.2', 'b3': '3.3', 'total': '3.19'},

src/reportes/templates/reportes/charts.html
<!DOCTYPE html>
{% extends 'base/base.html'%}
{% load staticfiles %}
{% load bootstrap3 %}


{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="row">
    <h1>Reportes</h1>
    <div class="col-sm-12" url-endpoint="{% url 'reportes:api-data' %}">

        <div class="btn-group btn-group-justified" role="group" aria-label="...">
  <div class="btn-group text-white" role="group">
    <a class="btn btn-primary" href="{% url 'reportes:report' %}"></i> Historial Prestamos</a>
  </div>
  <div class="btn-group text-white" role="group">
    <a class="btn btn-primary" href="{% url 'reportes:report_activo' %}"></i> Prestamos Activos</a>
  </div>
  <div class="btn-group text-white" role="group">
    <a class="btn btn-primary" href="{% url 'reportes:report' %}"></i> Productos Mas Usados</a>
  </div>
</div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
        <div class="col-md-6 col-md-offset-3">
            <canvas id="myChart" width="400" height="400"></canvas>
        </div>
    </div>
</div>

<script>
var endpoint = 'api/chart/data/'
var defaultData = []
var labels = []

$.ajax({
    method: "GET",
    url: endpoint,
    success: function (data) {
        labels = data.labels
        defaultData = data.default
        setChart()

    },
    error: function (error_data) {
        console.log("error")
        console.log(error_data)
    }
})

function setChart() {
    var ctx = document.getElementById("myChart");
    //var ctx2 = document.getElementById("myChart2");
    // var myChart = new Chart(ctx2, {
    //     type: 'bar',
    //     data: {
    //         labels: labels,
    //         datasets: [{
    //             label: '# of Votes',
    //             data: defaultData,
    //             backgroundColor: [
    //                 'rgba(255, 99, 132, 0.2)',
    //                 'rgba(54, 162, 235, 0.2)',
    //                 'rgba(255, 206, 86, 0.2)',
    //                 'rgba(75, 192, 192, 0.2)',
    //                 'rgba(153, 102, 255, 0.2)',
    //                 'rgba(255, 159, 64, 0.2)'
    //             ],
    //             borderColor: [
    //                 'rgba(255,99,132,1)',
    //                 'rgba(54, 162, 235, 1)',
    //                 'rgba(255, 206, 86, 1)',
    //                 'rgba(75, 192, 192, 1)',
    //                 'rgba(153, 102, 255, 1)',
    //                 'rgba(255, 159, 64, 1)'
    //             ],
    //             borderWidth: 1
    //         }]
    //     },
    //     options: {
    //         scales: {
    //             yAxes: [{
    //                 ticks: {
    //                     beginAtZero: true
    //                 }
    //             }]
    //         }
    //     }
    // });

    var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: labels,
        datasets: [{
            label: '# of Votes',
            data: defaultData,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
}

// var ctx = document.getElementById("myChart").getContext('2d');
// var myChart = new Chart(ctx, {
//     type: 'bar',
//     data: {
//         labels: labels,
//         datasets: [{
//             label: '# of Votes',
//             data: defaultData,
//             backgroundColor: [
//                 'rgba(255, 99, 132, 0.2)',
//                 'rgba(54, 162, 235, 0.2)',
//                 'rgba(255, 206, 86, 0.2)',
//                 'rgba(75, 192, 192, 0.2)',
//                 'rgba(153, 102, 255, 0.2)',
//                 'rgba(255, 159, 64, 0.2)'
//             ],
//             borderColor: [
//                 'rgba(255,99,132,1)',
//                 'rgba(54, 162, 235, 1)',
//                 'rgba(255, 206, 86, 1)',
//                 'rgba(75, 192, 192, 1)',
//                 'rgba(153, 102, 255, 1)',
//                 'rgba(255, 159, 64, 1)'
//             ],
//             borderWidth: 1
//         }]
//     },
//     options: {
//         scales: {
//             yAxes: [{
//                 ticks: {
//                     beginAtZero:true
//                 }
//             }]
//         }
//     }
// });
</script>
</body>
</html>

{% endblock %}

src/reportes/templates/reportes/prestamos_activos.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Reporte de Prestamos</title>
</head>
{% extends 'base/base.html' %}
{% block content %}
<div class='form-group'>
    <div class="row">
        <div class="col-lg-1">
            <a href="{% url 'reportes:report_activo' %}" class="btn btn-info btn-block">
                <span class=""></span>
            </a>
        </div>
    </div>
</div>
</html>
{% endblock %}

src/reportes/templates/reportes/pruea.html
<!DOCTYPE html>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="row">
    <div class="col-sm-12" url-endpoint="{% url 'reportes:api-data' %}">
        <h1>Hello World</h1>
        <canvas id="myChart" width="400" height="400"></canvas>
    </div>
</div>

<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>
</body>
</html>

src/reportes/templates/reportes/reportes_prestamo.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Reporte de Prestamos</title>
</head>
{% extends 'base/base.html' %}
{% block content %}
<div class='form-group'>
    <div class="row">
        <div class="col-lg-1">
            <a href="{% url 'reportes:prestamo_reporte' %}" class="btn btn-info btn-block">
                <span class=""></span>
            </a>
        </div>
    </div>
</div>
</html>
{% endblock %}